name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: check java version
      run: java -version
    - name: set gradlew excuteable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build aR
    - name: show error log
      run: cat /home/runner/work/AndroidProject-Kotlin/AndroidProject-Kotlin/app/build/intermediates/lint_intermediate_text_report/debug/lintReportDebug/lint-results-debug.txt
