name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
    - uses: actions/setup-java@v4.5.0
      with:
        java-version: 17
        distribution: jdk
    - name: check java version
      run: java -version
    - name: set gradlew excuteable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build aR
